/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IUniswapV4DynamicPriceRouter,
  IUniswapV4DynamicPriceRouterInterface,
} from "../../router/IUniswapV4DynamicPriceRouter";

const _abi = [
  {
    inputs: [],
    name: "FEE_DENOMINATOR",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "ROUTER_NAME",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "ICustomUniswapV4Router.Currency",
            name: "exactCurrency",
            type: "address",
          },
          {
            components: [
              {
                internalType: "ICustomUniswapV4Router.Currency",
                name: "intermediateCurrency",
                type: "address",
              },
              {
                internalType: "uint24",
                name: "fee",
                type: "uint24",
              },
              {
                internalType: "int24",
                name: "tickSpacing",
                type: "int24",
              },
              {
                internalType: "contract IHooks",
                name: "hooks",
                type: "address",
              },
              {
                internalType: "bytes",
                name: "hookData",
                type: "bytes",
              },
            ],
            internalType: "struct ICustomUniswapV4Router.PathKey[]",
            name: "path",
            type: "tuple[]",
          },
          {
            internalType: "uint128",
            name: "exactAmount",
            type: "uint128",
          },
        ],
        internalType: "struct ICustomUniswapV4Router.QuoteExactParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "ICustomUniswapV4Router.Currency",
            name: "exactCurrency",
            type: "address",
          },
          {
            components: [
              {
                internalType: "ICustomUniswapV4Router.Currency",
                name: "intermediateCurrency",
                type: "address",
              },
              {
                internalType: "uint24",
                name: "fee",
                type: "uint24",
              },
              {
                internalType: "int24",
                name: "tickSpacing",
                type: "int24",
              },
              {
                internalType: "contract IHooks",
                name: "hooks",
                type: "address",
              },
              {
                internalType: "bytes",
                name: "hookData",
                type: "bytes",
              },
            ],
            internalType: "struct ICustomUniswapV4Router.PathKey[]",
            name: "path",
            type: "tuple[]",
          },
          {
            internalType: "uint128",
            name: "exactAmount",
            type: "uint128",
          },
        ],
        internalType: "struct ICustomUniswapV4Router.QuoteExactParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "getPriceFeesRemoved",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IUniswapV4DynamicPriceRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IUniswapV4DynamicPriceRouterInterface {
    return new Interface(_abi) as IUniswapV4DynamicPriceRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IUniswapV4DynamicPriceRouter {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IUniswapV4DynamicPriceRouter;
  }
}
