/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IUniswapV3DynamicPriceRouter,
  IUniswapV3DynamicPriceRouterInterface,
} from "../../router/IUniswapV3DynamicPriceRouter";

const _abi = [
  {
    inputs: [],
    name: "ROUTER_NAME",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum IUniswapV3DynamicPriceRouter.Fee",
        name: "fee",
        type: "uint8",
      },
    ],
    name: "getFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "path",
        type: "bytes",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "path",
        type: "bytes",
      },
      {
        internalType: "enum IUniswapV3DynamicPriceRouter.Fee[]",
        name: "fees",
        type: "uint8[]",
      },
    ],
    name: "getPriceFeesRemoved",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IUniswapV3DynamicPriceRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IUniswapV3DynamicPriceRouterInterface {
    return new Interface(_abi) as IUniswapV3DynamicPriceRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IUniswapV3DynamicPriceRouter {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IUniswapV3DynamicPriceRouter;
  }
}
