/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ICustomUniswapV4Router {
  export type PathKeyStruct = {
    intermediateCurrency: AddressLike;
    fee: BigNumberish;
    tickSpacing: BigNumberish;
    hooks: AddressLike;
    hookData: BytesLike;
  };

  export type PathKeyStructOutput = [
    intermediateCurrency: string,
    fee: bigint,
    tickSpacing: bigint,
    hooks: string,
    hookData: string
  ] & {
    intermediateCurrency: string;
    fee: bigint;
    tickSpacing: bigint;
    hooks: string;
    hookData: string;
  };

  export type QuoteExactParamsStruct = {
    exactCurrency: AddressLike;
    path: ICustomUniswapV4Router.PathKeyStruct[];
    exactAmount: BigNumberish;
  };

  export type QuoteExactParamsStructOutput = [
    exactCurrency: string,
    path: ICustomUniswapV4Router.PathKeyStructOutput[],
    exactAmount: bigint
  ] & {
    exactCurrency: string;
    path: ICustomUniswapV4Router.PathKeyStructOutput[];
    exactAmount: bigint;
  };
}

export interface ICustomUniswapV4RouterInterface extends Interface {
  getFunction(nameOrSignature: "quoteExactInput"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "quoteExactInput",
    values: [ICustomUniswapV4Router.QuoteExactParamsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "quoteExactInput",
    data: BytesLike
  ): Result;
}

export interface ICustomUniswapV4Router extends BaseContract {
  connect(runner?: ContractRunner | null): ICustomUniswapV4Router;
  waitForDeployment(): Promise<this>;

  interface: ICustomUniswapV4RouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  quoteExactInput: TypedContractMethod<
    [params: ICustomUniswapV4Router.QuoteExactParamsStruct],
    [[bigint, bigint] & { amountOut: bigint; gasEstimate: bigint }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "quoteExactInput"
  ): TypedContractMethod<
    [params: ICustomUniswapV4Router.QuoteExactParamsStruct],
    [[bigint, bigint] & { amountOut: bigint; gasEstimate: bigint }],
    "nonpayable"
  >;

  filters: {};
}
