/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface UniswapV2DynamicERC20Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "allowance"
      | "allowanceQuote"
      | "approve"
      | "balanceOf"
      | "balanceOfQuote"
      | "baseToken"
      | "decimals"
      | "dynamicPriceRouter"
      | "getBaseToQuotePath"
      | "getBaseTokenAmount"
      | "getBaseTokenPrice"
      | "getQuoteToBasePath"
      | "getQuoteTokenAmount"
      | "name"
      | "owner"
      | "pendingOwner"
      | "quoteToken"
      | "renounceOwnership"
      | "routerName"
      | "setBaseToQuotePath"
      | "setDynamicPriceRouter"
      | "setQuoteToBasePath"
      | "supportsInterface"
      | "symbol"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "DynamicPriceRouterSet"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Transfer"
      | "UniswapV2BaseToQuotePathSet"
      | "UniswapV2QuoteToBasePathSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowanceQuote",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfQuote",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "baseToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "dynamicPriceRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBaseToQuotePath",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBaseTokenAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBaseTokenPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getQuoteToBasePath",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getQuoteTokenAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quoteToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "routerName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseToQuotePath",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setDynamicPriceRouter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setQuoteToBasePath",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allowanceQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "baseToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dynamicPriceRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBaseToQuotePath",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBaseTokenAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBaseTokenPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuoteToBasePath",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuoteTokenAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quoteToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "routerName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBaseToQuotePath",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDynamicPriceRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setQuoteToBasePath",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DynamicPriceRouterSetEvent {
  export type InputTuple = [
    dynamicERC20: AddressLike,
    dynamicPriceRouter: AddressLike
  ];
  export type OutputTuple = [dynamicERC20: string, dynamicPriceRouter: string];
  export interface OutputObject {
    dynamicERC20: string;
    dynamicPriceRouter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UniswapV2BaseToQuotePathSetEvent {
  export type InputTuple = [
    dynamicERC20: AddressLike,
    baseToken: AddressLike,
    quoteToken: AddressLike,
    baseToQuotePath: AddressLike[]
  ];
  export type OutputTuple = [
    dynamicERC20: string,
    baseToken: string,
    quoteToken: string,
    baseToQuotePath: string[]
  ];
  export interface OutputObject {
    dynamicERC20: string;
    baseToken: string;
    quoteToken: string;
    baseToQuotePath: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UniswapV2QuoteToBasePathSetEvent {
  export type InputTuple = [
    dynamicERC20: AddressLike,
    baseToken: AddressLike,
    quoteToken: AddressLike,
    quoteToBasePath: AddressLike[]
  ];
  export type OutputTuple = [
    dynamicERC20: string,
    baseToken: string,
    quoteToken: string,
    quoteToBasePath: string[]
  ];
  export interface OutputObject {
    dynamicERC20: string;
    baseToken: string;
    quoteToken: string;
    quoteToBasePath: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UniswapV2DynamicERC20 extends BaseContract {
  connect(runner?: ContractRunner | null): UniswapV2DynamicERC20;
  waitForDeployment(): Promise<this>;

  interface: UniswapV2DynamicERC20Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  allowanceQuote: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  balanceOfQuote: TypedContractMethod<
    [_account: AddressLike],
    [bigint],
    "view"
  >;

  baseToken: TypedContractMethod<[], [string], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  dynamicPriceRouter: TypedContractMethod<[], [string], "view">;

  getBaseToQuotePath: TypedContractMethod<[], [string[]], "view">;

  getBaseTokenAmount: TypedContractMethod<
    [quoteTokenAmount: BigNumberish],
    [[string, bigint]],
    "view"
  >;

  getBaseTokenPrice: TypedContractMethod<[], [bigint], "view">;

  getQuoteToBasePath: TypedContractMethod<[], [string[]], "view">;

  getQuoteTokenAmount: TypedContractMethod<
    [baseTokenAmount: BigNumberish],
    [[string, bigint]],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  quoteToken: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  routerName: TypedContractMethod<[], [string], "view">;

  setBaseToQuotePath: TypedContractMethod<
    [_baseToQuotePath: AddressLike[]],
    [void],
    "nonpayable"
  >;

  setDynamicPriceRouter: TypedContractMethod<
    [_dynamicPriceRouter: AddressLike],
    [void],
    "nonpayable"
  >;

  setQuoteToBasePath: TypedContractMethod<
    [_quoteToBasePath: AddressLike[]],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  transferFrom: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "allowanceQuote"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOfQuote"
  ): TypedContractMethod<[_account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dynamicPriceRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBaseToQuotePath"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBaseTokenAmount"
  ): TypedContractMethod<
    [quoteTokenAmount: BigNumberish],
    [[string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBaseTokenPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getQuoteToBasePath"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getQuoteTokenAmount"
  ): TypedContractMethod<
    [baseTokenAmount: BigNumberish],
    [[string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quoteToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "routerName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setBaseToQuotePath"
  ): TypedContractMethod<
    [_baseToQuotePath: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDynamicPriceRouter"
  ): TypedContractMethod<
    [_dynamicPriceRouter: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setQuoteToBasePath"
  ): TypedContractMethod<
    [_quoteToBasePath: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "DynamicPriceRouterSet"
  ): TypedContractEvent<
    DynamicPriceRouterSetEvent.InputTuple,
    DynamicPriceRouterSetEvent.OutputTuple,
    DynamicPriceRouterSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "UniswapV2BaseToQuotePathSet"
  ): TypedContractEvent<
    UniswapV2BaseToQuotePathSetEvent.InputTuple,
    UniswapV2BaseToQuotePathSetEvent.OutputTuple,
    UniswapV2BaseToQuotePathSetEvent.OutputObject
  >;
  getEvent(
    key: "UniswapV2QuoteToBasePathSet"
  ): TypedContractEvent<
    UniswapV2QuoteToBasePathSetEvent.InputTuple,
    UniswapV2QuoteToBasePathSetEvent.OutputTuple,
    UniswapV2QuoteToBasePathSetEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "DynamicPriceRouterSet(address,address)": TypedContractEvent<
      DynamicPriceRouterSetEvent.InputTuple,
      DynamicPriceRouterSetEvent.OutputTuple,
      DynamicPriceRouterSetEvent.OutputObject
    >;
    DynamicPriceRouterSet: TypedContractEvent<
      DynamicPriceRouterSetEvent.InputTuple,
      DynamicPriceRouterSetEvent.OutputTuple,
      DynamicPriceRouterSetEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "UniswapV2BaseToQuotePathSet(address,address,address,address[])": TypedContractEvent<
      UniswapV2BaseToQuotePathSetEvent.InputTuple,
      UniswapV2BaseToQuotePathSetEvent.OutputTuple,
      UniswapV2BaseToQuotePathSetEvent.OutputObject
    >;
    UniswapV2BaseToQuotePathSet: TypedContractEvent<
      UniswapV2BaseToQuotePathSetEvent.InputTuple,
      UniswapV2BaseToQuotePathSetEvent.OutputTuple,
      UniswapV2BaseToQuotePathSetEvent.OutputObject
    >;

    "UniswapV2QuoteToBasePathSet(address,address,address,address[])": TypedContractEvent<
      UniswapV2QuoteToBasePathSetEvent.InputTuple,
      UniswapV2QuoteToBasePathSetEvent.OutputTuple,
      UniswapV2QuoteToBasePathSetEvent.OutputObject
    >;
    UniswapV2QuoteToBasePathSet: TypedContractEvent<
      UniswapV2QuoteToBasePathSetEvent.InputTuple,
      UniswapV2QuoteToBasePathSetEvent.OutputTuple,
      UniswapV2QuoteToBasePathSetEvent.OutputObject
    >;
  };
}
