/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPurchaseManager__factory } from "./IPurchaseManager__factory";
export { PurchaseManager__factory } from "./PurchaseManager__factory";
