/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ISubscriptionEscrow {
  export type SubscriptionStruct = {
    orgId: BigNumberish;
    pricingId: BigNumberish;
    startDate: BigNumberish;
    endDate: BigNumberish;
    timeRemaining: BigNumberish;
    isCancelled: boolean;
    isPaused: boolean;
  };

  export type SubscriptionStructOutput = [
    orgId: bigint,
    pricingId: bigint,
    startDate: bigint,
    endDate: bigint,
    timeRemaining: bigint,
    isCancelled: boolean,
    isPaused: boolean
  ] & {
    orgId: bigint;
    pricingId: bigint;
    startDate: bigint;
    endDate: bigint;
    timeRemaining: bigint;
    isCancelled: boolean;
    isPaused: boolean;
  };
}

export declare namespace IRenewalProcessor {
  export type PassRenewalStatusStruct = {
    passId: BigNumberish;
    productId: BigNumberish;
    subscription: ISubscriptionEscrow.SubscriptionStruct;
    subStatus: BigNumberish;
    renewalStatus: BigNumberish;
  };

  export type PassRenewalStatusStructOutput = [
    passId: bigint,
    productId: bigint,
    subscription: ISubscriptionEscrow.SubscriptionStructOutput,
    subStatus: bigint,
    renewalStatus: bigint
  ] & {
    passId: bigint;
    productId: bigint;
    subscription: ISubscriptionEscrow.SubscriptionStructOutput;
    subStatus: bigint;
    renewalStatus: bigint;
  };
}

export interface RenewalProcessorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllPassRenewalStatus"
      | "getAllPassRenewalStatusBatch"
      | "getSingleProductRenewalStatus"
      | "processAllPassRenewal"
      | "processAllPassRenewalBatch"
      | "processSingleProductRenewal"
      | "registry"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RenewalProcessed"): EventFragment;

  encodeFunctionData(
    functionFragment: "getAllPassRenewalStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllPassRenewalStatusBatch",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSingleProductRenewalStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processAllPassRenewal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processAllPassRenewalBatch",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processSingleProductRenewal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllPassRenewalStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllPassRenewalStatusBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSingleProductRenewalStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processAllPassRenewal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processAllPassRenewalBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processSingleProductRenewal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace RenewalProcessedEvent {
  export type InputTuple = [
    orgId: BigNumberish,
    productPassId: BigNumberish,
    productId: BigNumberish,
    status: BigNumberish
  ];
  export type OutputTuple = [
    orgId: bigint,
    productPassId: bigint,
    productId: bigint,
    status: bigint
  ];
  export interface OutputObject {
    orgId: bigint;
    productPassId: bigint;
    productId: bigint;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RenewalProcessor extends BaseContract {
  connect(runner?: ContractRunner | null): RenewalProcessor;
  waitForDeployment(): Promise<this>;

  interface: RenewalProcessorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllPassRenewalStatus: TypedContractMethod<
    [_passId: BigNumberish],
    [IRenewalProcessor.PassRenewalStatusStructOutput[]],
    "view"
  >;

  getAllPassRenewalStatusBatch: TypedContractMethod<
    [_startPassId: BigNumberish, _endPassId: BigNumberish],
    [IRenewalProcessor.PassRenewalStatusStructOutput[][]],
    "view"
  >;

  getSingleProductRenewalStatus: TypedContractMethod<
    [_passId: BigNumberish, _productId: BigNumberish],
    [IRenewalProcessor.PassRenewalStatusStructOutput],
    "view"
  >;

  processAllPassRenewal: TypedContractMethod<
    [_passId: BigNumberish],
    [void],
    "nonpayable"
  >;

  processAllPassRenewalBatch: TypedContractMethod<
    [_startPassId: BigNumberish, _endPassId: BigNumberish],
    [void],
    "nonpayable"
  >;

  processSingleProductRenewal: TypedContractMethod<
    [_passId: BigNumberish, _productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllPassRenewalStatus"
  ): TypedContractMethod<
    [_passId: BigNumberish],
    [IRenewalProcessor.PassRenewalStatusStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllPassRenewalStatusBatch"
  ): TypedContractMethod<
    [_startPassId: BigNumberish, _endPassId: BigNumberish],
    [IRenewalProcessor.PassRenewalStatusStructOutput[][]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSingleProductRenewalStatus"
  ): TypedContractMethod<
    [_passId: BigNumberish, _productId: BigNumberish],
    [IRenewalProcessor.PassRenewalStatusStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "processAllPassRenewal"
  ): TypedContractMethod<[_passId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "processAllPassRenewalBatch"
  ): TypedContractMethod<
    [_startPassId: BigNumberish, _endPassId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "processSingleProductRenewal"
  ): TypedContractMethod<
    [_passId: BigNumberish, _productId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "RenewalProcessed"
  ): TypedContractEvent<
    RenewalProcessedEvent.InputTuple,
    RenewalProcessedEvent.OutputTuple,
    RenewalProcessedEvent.OutputObject
  >;

  filters: {
    "RenewalProcessed(uint256,uint256,uint256,uint8)": TypedContractEvent<
      RenewalProcessedEvent.InputTuple,
      RenewalProcessedEvent.OutputTuple,
      RenewalProcessedEvent.OutputObject
    >;
    RenewalProcessed: TypedContractEvent<
      RenewalProcessedEvent.InputTuple,
      RenewalProcessedEvent.OutputTuple,
      RenewalProcessedEvent.OutputObject
    >;
  };
}
