/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IProductPassNFT,
  IProductPassNFTInterface,
} from "../../tokens/IProductPassNFT";

const _abi = [
  {
    inputs: [],
    name: "ProductsNotTransferable",
    type: "error",
  },
  {
    inputs: [],
    name: "SubscriptionsNotTransferable",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IProductPassNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IProductPassNFTInterface {
    return new Interface(_abi) as IProductPassNFTInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IProductPassNFT {
    return new Contract(address, _abi, runner) as unknown as IProductPassNFT;
  }
}
