/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IOrganizationAdmin } from "./IOrganizationAdmin";
export type { OrganizationAdmin } from "./OrganizationAdmin";
