/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IOrganizationAdmin__factory } from "./IOrganizationAdmin__factory";
export { OrganizationAdmin__factory } from "./OrganizationAdmin__factory";
